### ISSUE TITLE
Designer's feedback and enhancements v1

### ISSUE THREAD

**Issue by jgresham** [NiceNode/bench-buddy-website#1]
Reviewed the site, mostly minor issues & tweaks I think, some feedback below + assets! 🙂

- [x] Favicon is a bit squeezed and hard to read, new proposal attached.
- [x] Top Image could be .svg (attached)
- [x] "Benchbuddy" title should be H1 instead of graphic, styled with css (font Satoshi-Black!). I've made a demo here: https://jsfiddle.net/danielgoy/8d2rg4za/
- [x] Links like "show example output" don't have hover effect. Hover effect = #000002 70% -> #000002 85% transparency.
- [x] Pre-requisite paragraph: "Podman" & "Docker" should be links to their websites.
- [x] Show documentation for docker/podman toggle: The inactive state has a solid gray instead of the #000002 transparency + No hover effect. I've put the states next to the page in the figma file.
- [x] command preview + code snippet box model: padding on the left, where the text starts should be greater.
- [x] command + code should be rendered in monospaced font. Google fonts like "Roboto Mono" or "Source Code Pro" should work great.
- [x] corner radius of the "copy" button should be smaller than the code container. So the roundness matches visually. (see figma)
- [x] The example code gets rendered outside it's container on smaller screens. Either the lines should break or we introduce a horizontal scrollbar.
- [x] Check font sizes on attributions + copyright footer. Also, remove capital R in CopyRight.
- [x] Below 1024 breakpoint: Content snaps to approx 450px wide. Content should be wider here.. On lower breakpoints a bit of the same problem, content should be wider. On the smallest widths, we should have a around 12 to 16px margin. Below 334 it just sticks to the edges.

SVG file: 
![BenchBuddy](https://github.com/NiceNode/bench-buddy-website/assets/3721291/9227b76c-57e4-4803-a8f2-a4159ee853d4)
New Favicon:
[BenchBuddy_Favicon.zip](https://github.com/NiceNode/bench-buddy-website/files/13419235/BenchBuddy_Favicon.zip)

**Comment by Gathin23** [comment]
@jgresham Have completed every modification suggested and tested it! 

Commit Details:

![image](https://github.com/NiceNode/bench-buddy-website/assets/94786511/d3b8a284-1053-4cc0-aec6-1e1044bd66dd)
